[template]
owner = "haproxy"
mode = "0644"
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"

check_cmd = "cat {{ .src }} && haproxy -c -f {{ .src }}"
reload_cmd = "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
